services:
  webpush:
    build:
      context: .
      dockerfile: ./images/websocket/Dockerfile
    ports:
      - "8081:8081"
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    command: start --all --config /etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}